<a href="https://colab.research.google.com/github/Einsteinium-99/Einsteinium-99/blob/main/RomelaML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import torch

## ***TENSORS***

In [43]:
t1 = torch.tensor(0.40)
t1.dtype

torch.float32

In [44]:
t2 = torch.tensor([[.1,.2,.4],[.1,.2,.4]])
t2

tensor([[0.1000, 0.2000, 0.4000],
        [0.1000, 0.2000, 0.4000]])

In [45]:
t3 = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t3)
t3.shape

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


torch.Size([2, 2, 3])

# **TENSOR OPERATIONS AND GRADIENTS**

In [46]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
y = w * x + b
y.backward() # derivates for variables that have requires_grad=True // works for any differentiable function (complex or not)
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


# ***INTEROPERABILITY WITH NUMPY***

In [47]:
import numpy as np

In [48]:
# Matplotlib, OpenCV, Pandas
x = np.array([[1,2],[1,2]])
y = torch.from_numpy(x) # uses the numpy data without creating a copy
z = torch.tensor(x) # creates copy of data
g = y.numpy() # convert tensor to numpy array
print(x.dtype, ' ', y.dtype, ' ', z.dtype, ' ', g.dtype)
g

int64   torch.int64   torch.int64   int64


array([[1, 2],
       [1, 2]])

# ***COMMIT AND UPLOAD THE NOTEBOOK***

In [49]:
!pip install jovian --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [50]:
import jovian

In [52]:
jovian.commit()

[jovian] Detected Colab notebook...


[jovian] Error: jovian.commit doesn't work on Colab unless the notebook was created and executed from Jovian.
Make sure to run the first code cell at the top after executing from Jovian.
Alternatively, you can download this notebook and upload it manually to Jovian.
Learn more: https://jovian.ai/docs/user-guide/run.html#run-on-colab
